### ISSUE TITLE
Issue mapping between primitives and wrappers

### ISSUE THREAD

**Issue by rsoffiatto** [dobrynya/nomin#29]
Hi,

I'm having a problem with mappings where one side is a primitive and the other is a wrapper.
For example, if I have the mapping:
```
class AToB extends org.nomin.Mapping {
    protected void build() {
        mappingFor a:A, b:B
        a.numberA = b.numberB
    }
}

class A {
    long numberA
}

class B {
    Long numberB
}```

mapping B to A works as expected but mapping A to B gives me the following error:
```
Could not find applicable mappings between java.lang.Long and java.lang.Long. A mapping will be created using automapping facility
Exception thrown

org.nomin.core.NominException: org.nomin.Mapping: Mapping rule a.long = b.long is invalid because of missing property Long.long!
	at org.nomin.core.PropPathElem.createMappingRuleElement(PropPathElem.groovy:18)
	at org.nomin.core.PropPathElem$createMappingRuleElement.call(Unknown Source)
	at org.nomin.core.RootPathElem$createMappingRuleElement.call(Unknown Source)
	at org.nomin.core.MappingEntry.buildRuleElem(MappingEntry.groovy:77)
	at org.nomin.core.MappingEntry.buildRuleElem(MappingEntry.groovy:79)
	at org.nomin.core.MappingEntry.buildRuleElem(MappingEntry.groovy)
	at org.nomin.core.MappingEntry$_parse_closure4.doCall(MappingEntry.groovy:51)
	at org.nomin.core.MappingEntry.parse(MappingEntry.groovy:49)
	at org.nomin.Mapping.parse(Mapping.groovy:44)
	at org.nomin.core.Nomin.findApplicable(Nomin.java:228)
	at org.nomin.core.Nomin.findCachedApplicable(Nomin.java:211)
	at org.nomin.core.Nomin.map(Nomin.java:201)
	at org.nomin.core.Nomin.map(Nomin.java:159)
	at org.nomin.core.preprocessing.MapperPreprocessing.preprocess(MapperPreprocessing.java:23)
	at org.nomin.core.preprocessing.Preprocessing.preprocess(Preprocessing.java:25)
	at org.nomin.core.PropRuleElem.set(PropRuleElem.java:27)
	at org.nomin.core.MappingRule.map(MappingRule.java:27)
	at org.nomin.core.MappingRule.mapAtoB(MappingRule.java:36)
	at org.nomin.core.ParsedMapping.map(ParsedMapping.java:104)
	at org.nomin.core.Nomin.map(Nomin.java:202)
	at org.nomin.core.Nomin.map(Nomin.java:159)
	at org.nomin.core.Nomin.map(Nomin.java:156)
	at org.nomin.NominMapper$map$0.call(Unknown Source)
	at ConsoleScript24.run(ConsoleScript24:9)
```

Using the exploding instrospector the message changes, but the error still happens the same way: wrapper to primitive works, primitive to wrapper fails:

```
Could not find applicable mappings between java.lang.Long and java.lang.Long. A mapping will be created using automapping facility
Exception thrown

org.nomin.core.NominException: AToB: Mapping rule numberA:long = numberB:Long has failed!
	at org.nomin.core.ParsedMapping.handle(ParsedMapping.java:70)
	at org.nomin.core.ParsedMapping.map(ParsedMapping.java:105)
	at org.nomin.core.Nomin.map(Nomin.java:202)
	at org.nomin.core.Nomin.map(Nomin.java:159)
	at org.nomin.core.Nomin.map(Nomin.java:156)
	at org.nomin.NominMapper$map$0.call(Unknown Source)
	at ConsoleScript21.run(ConsoleScript21:9)
Caused by: org.nomin.core.NominException: Could not instantiate class java.lang.Long!
	at org.nomin.core.ParsedMapping.map(ParsedMapping.java:88)
	at org.nomin.core.Nomin.map(Nomin.java:202)
	at org.nomin.core.Nomin.map(Nomin.java:159)
	at org.nomin.core.preprocessing.MapperPreprocessing.preprocess(MapperPreprocessing.java:23)
	at org.nomin.core.preprocessing.Preprocessing.preprocess(Preprocessing.java:25)
	at org.nomin.core.PropRuleElem.set(PropRuleElem.java:27)
	at org.nomin.core.MappingRule.map(MappingRule.java:27)
	at org.nomin.core.MappingRule.mapAtoB(MappingRule.java:36)
	at org.nomin.core.ParsedMapping.map(ParsedMapping.java:104)
	... 5 more
Caused by: java.lang.InstantiationException: java.lang.Long
	at org.nomin.util.ReflectionInstanceCreator.create(ReflectionInstanceCreator.java:9)
	at org.nomin.core.ParsedMapping.map(ParsedMapping.java:87)
	... 13 more
Caused by: java.lang.NoSuchMethodException: java.lang.Long.<init>()
	... 15 more
```

**Comment by dobrynya** [comment]
Hi @rsoffiatto 
Give me some time to research the issue
Best regards

**Comment by dobrynya** [comment]
You have found a bug. I've fixed it. I'm releasing nomin v1.1.5.

**Comment by dobrynya** [comment]
@rsoffiatto please upgrade nomin up to v1.1.5 (released today) and test your use case again. The issue should go away.

**Comment by dobrynya** [comment]
@rsoffiatto please upgrade nomin up to v1.1.6. There is all required artifacts in Maven Central -- http://central.maven.org/maven2/net/sf/nomin/nomin/1.1.6
Please notify me whether nomin works for you as expected
